In [ ]:
# Spotify 2024 Analysis - Initial Exploration

# This notebook covers:
# 1. Loading the data
# 2. Initial exploration
# 3. Basic visualizations

In [2]:
# 1. Import Libraries

import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
from pathlib import Path

print("Libraries imported successfully")

# Set up visualization style
plt.style.use('seaborn-v0_8')
plt.rcParams['figure.figsize'] = (12, 8)
plt.rcParams['font.size'] = 10
print("Visualization style set")

# See all the columns and rows

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)
print("Format Columns and Rows set")

Libraries imported successfully
Visualization style set
Format Columns and Rows set

In [3]:
# 2. Load Data   

# 2.1. Finds the project root by looking for your data file

def find_project_root(marker_file="Most Streamed Spotify Songs 2024.csv"):
    current_path = Path(os.getcwd())
    
    # Search upward through parent folders
    for parent in [current_path] + list(current_path.parents):
        # Check for Data folder with target file
        data_path = parent / "Data" / marker_file
        if data_path.exists():
            print(f" Found project root: {parent}")
            return parent
        
        # Alternative: check for file directly in parent
        if (parent / marker_file).exists():
            print(f" Found project root: {parent}")
            return parent
    
    # If not found
    print(" Could not locate project root containing your data file")
    print(f"Searching for: {marker_file}")
    print(f"Search path: {current_path} -> {current_path.parents[-1]}")
    return None

# Usage:
project_root = find_project_root()
if project_root:
    os.chdir(project_root)  # Change to project root
    print(f" Working directory set to: {project_root}")

 Found project root: c:\ARCHIVOS\DOCUMENTS\Mary\Alvaro\Portfolio\Python\Project 1
 Working directory set to: c:\ARCHIVOS\DOCUMENTS\Mary\Alvaro\Portfolio\Python\Project 1

In [6]:
# 2.2. Load Data

def load_data():

    encodings = ['latin-1', 'utf-8', 'utf-8-sig', 'iso-8859-1', 'cp1252']
    
    for encoding in encodings:
        try:
            data_path = Path("Data") / "Most Streamed Spotify Songs 2024.csv"
            if data_path.exists():
                df = pd.read_csv(data_path, encoding=encoding)
                print(f" Successfully loaded with {encoding} encoding")
                return df
        except Exception as e:
            print(f" Failed with {encoding}: {str(e)[:100]}...")
    
    print("\n Try these solutions:")
    print("1. Verify the file exists in the Data folder")
    print("2. Check for file corruption")
    print(f"3. Current directory: {Path.cwd()}")
    return None

print("=== Starting Data Load ===")
project_root = find_project_root()
if project_root:
    os.chdir(project_root)
    
    df = load_data()  
    
    if df is not None:
        print("\n=== Data Loaded Successfully ===")
        print(f"Shape: {df.shape}")
        print("\nFirst 5 rows:")
        display(df.head(5))
    else:
        print("\n Failed to load DataFrame")
else:
    print("\n Cannot proceed without project root")

=== Starting Data Load ===
 Found project root: c:\ARCHIVOS\DOCUMENTS\Mary\Alvaro\Portfolio\Python\Project 1
 Successfully loaded with latin-1 encoding

=== Data Loaded Successfully ===
Shape: (4600, 29)

First 5 rows:

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,YouTube Likes,TikTok Posts,TikTok Likes,TikTok Views,YouTube Playlist Reach,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,QM24S2402528,1,725.40,"390,470,936","30,716","196,631,588",92.00,"84,274,754","1,713,126","5,767,700","651,565,900","5,332,281,936","150,597,040",210.00,"40,975",684,62.00,"17,598,718",114.00,"18,004,655","22,931","4,818,457","2,669,262",NaN,0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,USUG12400910,2,545.90,"323,703,884","28,113","174,597,137",92.00,"116,347,040","3,486,739","674,700","35,223,547","208,339,025","156,380,351",188.00,"40,778",3,67.00,"10,422,430",111.00,"7,780,028","28,444","6,623,075","1,118,279",NaN,1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,QZJ842400387,3,538.40,"601,309,283","54,331","211,607,669",92.00,"122,599,116","2,228,730","3,025,400","275,154,237","3,369,120,610","373,784,955",190.00,"74,333",536,136.00,"36,321,847",172.00,"5,022,621","5,639","7,208,651","5,285,340",NaN,0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,USSM12209777,4,444.90,"2,031,280,633","269,802","136,569,078",85.00,"1,096,100,899","10,629,796","7,189,811","1,078,757,968","14,603,725,994","3,351,188,582",394.00,"1,474,799","2,182",264.00,"24,684,248",210.00,"190,260,277","203,384",NaN,"11,822,942",NaN,0
4,Houdini,Houdini,Eminem,5/31/2024,USUG12403398,5,423.30,"107,034,922","7,223","151,469,874",88.00,"77,373,957","3,670,188","16,400",NaN,NaN,"112,763,851",182.00,"12,185",1,82.00,"17,660,624",105.00,"4,493,884","7,006","207,179","457,017",NaN,1

In [5]:
# 3. Initial Exploration

if df is not None:
    print("\n=== Data Exploration ===")
    
    # 3.1 Basic info
    print("\n1. Basic Info:\n")
    print(f"- Total songs: {len(df):,}")
    print(f"- Columns: {list(df.columns)}")
    
    # 3.2 Data types
    print("\n2. Data Types:\n")
    display(df.dtypes.to_frame('Data Type'))
    
    # 3.3 Missing values
    missing_data = df.isnull().sum()
    total_missing = missing_data.sum()
    print("\n3. Missing values:\n") 
    if total_missing == 0:
        print("No missing values found!")
    else:
        print(missing_data[missing_data > 0].sort_values(ascending=False))

    # 3.4 Duplicates
    duplicate_count = df.duplicated().sum()
    print(f"\n4. Duplicate rows: {duplicate_count}")
    df[df.duplicated(keep=False)]

    # 3.5 Unique Values    
    print("\n5. Unique Values per column:\n")
    unique_counts = (df.nunique()
                    .reset_index()
                    .rename(columns={'index': 'Column', 0: 'Unique Values'})
                    .sort_values('Unique Values', ascending=False))
    unique_counts['% Unique'] = (unique_counts['Unique Values'] / len(df) * 100).round(1)
    display(unique_counts)

    # 3.6 Quick stats
    print("\n6. Quick Stats:\n")
    display(df.describe().transpose())

=== Data Exploration ===

1. Basic Info:

- Total songs: 4,600
- Columns: ['Track', 'Album Name', 'Artist', 'Release Date', 'ISRC', 'All Time Rank', 'Track Score', 'Spotify Streams', 'Spotify Playlist Count', 'Spotify Playlist Reach', 'Spotify Popularity', 'YouTube Views', 'YouTube Likes', 'TikTok Posts', 'TikTok Likes', 'TikTok Views', 'YouTube Playlist Reach', 'Apple Music Playlist Count', 'AirPlay Spins', 'SiriusXM Spins', 'Deezer Playlist Count', 'Deezer Playlist Reach', 'Amazon Playlist Count', 'Pandora Streams', 'Pandora Track Stations', 'Soundcloud Streams', 'Shazam Counts', 'TIDAL Popularity', 'Explicit Track']

2. Data Types:

                           Data Type
Track                         object
Album Name                    object
Artist                        object
Release Date                  object
ISRC                          object
All Time Rank                 object
Track Score                  float64
Spotify Streams               object
Spotify Playlist Count        object
Spotify Playlist Reach        object
Spotify Popularity           float64
YouTube Views                 object
YouTube Likes                 object
TikTok Posts                  object
TikTok Likes                  object
TikTok Views                  object
YouTube Playlist Reach        object
Apple Music Playlist Count   float64
AirPlay Spins                 object
SiriusXM Spins                object
Deezer Playlist Count        float64
Deezer Playlist Reach         object
Amazon Playlist Count        float64
Pandora Streams               object
Pandora Track Stations        object
Soundcloud Streams            object
Shazam Counts                 object
TIDAL Popularity             float64
Explicit Track                 int64

3. Missing values:

TIDAL Popularity              4600
Soundcloud Streams            3333
SiriusXM Spins                2123
Pandora Track Stations        1268
TikTok Posts                  1173
Pandora Streams               1106
Amazon Playlist Count         1055
YouTube Playlist Reach        1009
TikTok Views                   981
TikTok Likes                   980
Deezer Playlist Reach          928
Deezer Playlist Count          921
Spotify Popularity             804
Shazam Counts                  577
Apple Music Playlist Count     561
AirPlay Spins                  498
YouTube Likes                  315
YouTube Views                  308
Spotify Streams                113
Spotify Playlist Reach          72
Spotify Playlist Count          70
Artist                           5
dtype: int64

4. Duplicate rows: 2

5. Unique Values per column:

                        Column  Unique Values  % Unique
4                         ISRC           4598    100.00
5                All Time Rank           4577     99.50
9       Spotify Playlist Reach           4478     97.30
7              Spotify Streams           4425     96.20
0                        Track           4370     95.00
11               YouTube Views           4290     93.30
12               YouTube Likes           4283     93.10
8       Spotify Playlist Count           4207     91.50
1                   Album Name           4005     87.10
26               Shazam Counts           4002     87.00
15                TikTok Views           3616     78.60
14                TikTok Likes           3615     78.60
21       Deezer Playlist Reach           3558     77.30
23             Pandora Streams           3491     75.90
16      YouTube Playlist Reach           3458     75.20
13                TikTok Posts           3318     72.10
18               AirPlay Spins           3267     71.00
24      Pandora Track Stations           2975     64.70
2                       Artist           1999     43.50
3                 Release Date           1562     34.00
25          Soundcloud Streams           1265     27.50
6                  Track Score            862     18.70
19              SiriusXM Spins            689     15.00
17  Apple Music Playlist Count            322      7.00
20       Deezer Playlist Count            233      5.10
22       Amazon Playlist Count            147      3.20
10          Spotify Popularity             94      2.00
28              Explicit Track              2      0.00
27            TIDAL Popularity              0      0.00

6. Quick Stats:

                             count  mean   std   min   25%   50%   75%    max
Track Score                4600.00 41.84 38.54 19.40 23.30 29.90 44.42 725.40
Spotify Popularity         3796.00 63.50 16.19  1.00 61.00 67.00 73.00  96.00
Apple Music Playlist Count 4039.00 54.60 71.61  1.00 10.00 28.00 70.00 859.00
Deezer Playlist Count      3679.00 32.31 54.27  1.00  5.00 15.00 37.00 632.00
Amazon Playlist Count      3545.00 25.35 25.99  1.00  8.00 17.00 34.00 210.00
TIDAL Popularity              0.00   NaN   NaN   NaN   NaN   NaN   NaN    NaN
Explicit Track             4600.00  0.36  0.48  0.00  0.00  0.00  1.00   1.00

In [ ]:
# 4. Basic Visualizations

def save_visualization(plot_name="artists_popularity.png"):

    # 1. Create folder explicitly 
    vis_dir = Path("Visualizations")
    
    # 2. Save with validation
    try:
        vis_dir.mkdir(exist_ok=True)  # Only creates if needed
        save_path = vis_dir / plot_name # Generate full save path
        plt.savefig(save_path, dpi=300, bbox_inches='tight', facecolor='white')
        print(f" Visualization saved to:\n{save_path.resolve()}")
        return True
    except Exception as e:
        print(f" Failed to save: {str(e)}\nAttempted path: {vis_dir.resolve()/plot_name}")
        return False

# Plot the Visualizations
if df is not None:
    plt.figure(figsize=(18, 7))
    
    # Plot 1: Top Artists
    plt.subplot(1, 2, 1)
    top_artists = df['Artist'].value_counts().head(10).sort_values()
    bars = top_artists.plot(kind='barh', color='#1DB954', edgecolor='black')
    plt.title("Top 10 Artists by Song Count", fontsize=14, pad=15)
    plt.xlabel("Number of Songs", fontsize=12)
    # Value Labels
    max_songs = top_artists.max()
    for i, v in enumerate(top_artists):
        bars.text(v + max_songs*0.02, i, f"{v:,}", va='center', fontsize=11)
    
    # Plot 2: Spotify Popularity 
    plt.subplot(1, 2, 2)
    n, bins, patches = plt.hist(df['Spotify Popularity'], bins=30,
                                color='#191414', edgecolor='#1DB954')
    
    # Reference lines with auto-positioned labels
    stats = {
        'Mean': (df['Spotify Popularity'].mean(), '#1DB954', '--'),
        'Median': (df['Spotify Popularity'].median(), '#FFA500', ':')
    }
    
    for i, (name, (value, color, linestyle)) in enumerate(stats.items()):
        plt.axvline(value, color=color, linestyle=linestyle, 
                   linewidth=2, ymin=0, ymax=1)
        plt.text(value + 1, plt.ylim()[1]*(0.95 - i*0.1),  # Stacked labels
                f"{name}: {value:.1f}", color=color, fontsize=12,
                bbox=dict(facecolor='white', alpha=0.7))

    # Axis formatting
    plt.title("Spotify Popularity Distribution\n(0-100 scale)", fontsize=14, pad=15)
    plt.xlabel("Popularity Score", fontsize=12)
    plt.ylabel("Number of Songs", fontsize=12)
    plt.xlim(0, 100)  # Fixed x-axis range
    plt.ylim(0, None)  # Force y-axis to start at 0

    # Save and Show
    plt.tight_layout(pad=3.0)
    if save_visualization():  
        plt.show()
    else:
        plt.close()

In [ ]:
# 5. Save a copy of the original data

def save_data_backup(df):
    os.makedirs("Data", exist_ok=True)
    save_path = Path("Data") / "spotify_raw_backup.csv"
    
    try:
        df.to_csv(save_path, index=False)
        print(f" Data saved to: {save_path.resolve()}")
    except Exception as e:
        print(f" Save failed: {str(e)}")

save_data_backup(df)

In [ ]:
# 6. Next Steps
print("\n Next Steps:")
print("1. Check the Visualizations/ folder for your plots")
print("2. Review the exploration results above")
print("3. In the next notebook we'll clean the data")